### ISSUE TITLE
AssertionError in BA Set and cVal set computation

### ISSUE THREAD

**Issue by MuvvalaKaran** [MuvvalaKaran/symbolic_synthesis#3]
What: AssertionError. 

I get the following error

```bash
Traceback (most recent call last):
  File "/root/symbolic_planning/src/main.py", line 225, in <module>
    regret_synthesis_handle.solve(verbose=False, just_adv_game=False, run_monitor=True, monolithic_tr=MONOLITHIC_TR)
  File "/root/symbolic_planning/src/src/symbolic_graphs/strategy_synthesis_scripts/franka_symbolic_regret_main.py", line 157, in solve
    self.graph_of_utls_handle.get_best_alternatives(mod_act_dict=self.mod_act_dict,
  File "/root/symbolic_planning/src/src/symbolic_graphs/symbolic_regret_graphs/symbolic_graph_of_utility.py", line 460, in get_best_alternatives
    assert self.ba_set.issubset(self.leaf_vals), f"Error computing set of beat alternatives. The BA set: [{self.ba_set}] should be a subset of utility values [{self.leaf_vals}]"
AssertionError: Error computing set of beat alternatives. The BA set: [{1.0, 3.0, 4.0, 5.0}] should be a subset of utility values [{1, 3, 4}]
```

When: running  a simple 2 block 5 loc example with `weighting_factor=3` for Regret Synthesis code with and without Monolithic TR flag set to true.

Why: The cause of the problem is this [line](https://github.com/aria-systems-group/sym_quant_reactive_synth/blob/7d2cb754ba9665ba1e2bc196da814c013281d8df/src/symbolic_graphs/symbolic_regret_graphs/symbolic_graph_of_utility.py#L437). Is this logic correct?

Problem File: 

```pddl
(define (problem dynamic_only_franka_world) (:domain dynamic_franka_box_world)
(:objects

    ;;;;; Locs where only the robot can operate ;;;;;
    
    l0 - box_loc
    l1 - box_loc

    ;;;;; Locs where the robot & human can operate ;;;;;
    ; NOTE: The way pyperplan parses the PDDL file, you need atleast two human locs to construct `human-move` action

    l6 - hbox_loc
    l7 - hbox_loc
    ;l8 - hbox_loc

    b0 - box
    b1 - box
)

;todo: put the initial state's facts and numeric values here
(:init
    (ready else)
    
    (on b0 l0)
    (on b1 l6)

)

(:goal 
(and
    (on b0 l0)
))

)
```

Task: 
```
 F(p01 | p17)
 ```

**Comment by MuvvalaKaran** [comment]
The code works correctly without the assertion  ([Link](https://github.com/aria-systems-group/sym_quant_reactive_synth/blob/7d2cb754ba9665ba1e2bc196da814c013281d8df/src/symbolic_graphs/symbolic_regret_graphs/symbolic_graph_of_utility.py#L460)). 

Should this line be removed?
